version: '3.5'
services:
  web:
    build: .
    environment:
      - TZ=Etc/UTC
    ports: 
      - target: 5000
        published: 5000
        protocol: tcp
        mode: host
    user: app
    entrypoint: "/bin/sh -x ./docker-entrypoint.sh"
    working_dir: "/home/app/MTC_Agent"
    container_name: Alpine_MTConnect_Agent
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./log/adapter.log
        target: /home/app/MTC_Agent/adapter.log
        consistency: delegated